apiVersion: v1
kind: Pod
metadata:
  name: api-persona-pod
  namespace: default
spec:
  containers:
    - name: api-container
      image: rruales06/api-persona:1.0.1
      ports:
        - containerPort: 8080
      env:
        - name: host
          value: localhost
        # - name: host
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.podIP
        - name: port
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          value: toor
        - name: MYSQL_ROOT_HOST
          value: "%"      
    - name: mariadb-container
      image: rruales06/bdd-api-persona:1.0.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: toor
        - name: MYSQL_ROOT_HOST
          value: "%"
      ports:
        - containerPort: 3306
