apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-persona-deployment
  namespace: name2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      containers:
        - name: api-container
          image: rruales06/api-persona:1.0.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: my-configmap-app