apiVersion: v1
kind: Pod
metadata:
  name: bdd-api-persona-pod
  namespace: name1
  labels:
    app: bdd-pod
  # pod de base de datos
spec:
  containers:
    - name: mariadb-container
      image: rruales06/bdd-api-persona:1.0.0
      envFrom:
        - configMapRef:
            name: my-configmap-bdd
      ports:
        - containerPort: 3306  