apiVersion: v1
kind: Service
metadata:
  name: my-bdd-service
  namespace: name1  # Optional: Replace with your namespace
spec:
  selector:
    app: bdd-pod       # Replace with the labels of your pods
  ports:
    - protocol: TCP
      port: 3306                # Port on the service
      targetPort: 3306        # Port on the pods
  type: ClusterIP  